[package]
name = "oat-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
oat-ast = { path = "../oat-ast", version = "0.1.0" }
