[package]
name = "llvmlite"
version = "0.1.0"
authors = ["Edward Minnix III <egregius313@gmail.com>"]
edition = "2021"

[dependencies.indexmap]
version = "^1.8"

[dependencies.oat-symbol]
path = "../oat-symbol"
version = "0.1.0"
